---
title: ""
author: ""
date: ""

output:
  html_document:
    theme: flatly
    css: assets/css/style.css
    toc: false
---

<nav class="navbar">

<div class="logo">
Martin Okwumuo
</div>

<ul class="nav-links">

<li><a href="index.html">Home</a></li>

<li><a href="about.html">About</a></li>

<li><a href="project.html">Projects</a></li>

<li><a href="dashboards.html">Dashboards</a></li>

<li><a href="resume/Martin_Okwumuo_Updated_CV.pdf">Resume</a></li>

<li><a href="contacts.html">Contact</a></li>

</ul>

</nav>

# Dashboard Gallery

*Explore a selection of dashboards that demonstrate my ability to transform raw data into actionable business insights.*

## U.S Freight Transportation Dashboard

**Business Problem**

Freight transportation involves large volumes of goods moving between locations through different transportation modes and commodity supply chains.

However, simply measuring the amount of freight being moved does not provide a complete picture of its economic importance. A relatively small physical volume of high-value goods may represent substantially greater economic value than a much larger volume of low-value commodities.

This project therefore examines both freight volume and freight value to understand:

- where freight activity is concentrated;
- which transportation modes carry the greatest freight volumes;
- which states account for the greatest freight activity and value;
- which commodities generate the greatest economic value; and
- which commodities have particularly high economic value relative to their physical weight.

**Tools**

R | Tableau | Git | GitHub

<div class="tableau-container">

<iframe
  src="https://public.tableau.com/views/U_S_FreightTransportAnalytics/U_SFreightTransportationAnalyticsDashboard?:showVizHome=no&:embed=true"
  width="100%"
  height="800"
  frameborder="0"
  allowfullscreen>
</iframe>

</div>

<div class="project-buttons">

<a href="https://public.tableau.com/views/U_S_FreightTransportAnalytics/U_SFreightTransportationAnalyticsDashboard?:showVizHome=no"
   target="_blank"
   class="project-button">
   View Full Tableau Dashboard
</a>

<a href="https://github.com/okwumuo-martin/Logistics-Operation-Dashboard"
   target="_blank"
   class="project-button">
   View GitHub Repository
</a>

<a href="projects/us-freight-transportation-analytics/U.S_freight_analytics.html"
   target="_blank"
   class="project-button">
    View Case Study
</a>

</div>

<div class="section-divider"></div>

## Natural Language Next-word Prediction App

This is a next-word prediction app; just like the "invisible AI" behind phone keyboards, search auto-complete, and drafting assistants. It was developed entirely from raw text, with no external APIs or pre-trained language models. It covers the full life-cycle of a real data science project; 

- Exploratory Data Analysis 
- Model Architecture several rounds of serious 
- Performance Debugging
- Evaluation 
- Data Product

**Tools**

R | Shiny | Git | GitHub

**Skills Demonstrated**

- Exploratory Data Analysis
- Applied Natural Language Processing
- Performance Engineering 
- Evaluation Methodology 
- Product Thinking
- R Engineering
- Machine Learning

<div class="tableau-container">

<iframe
  src="https://snndvl-martin-okwumuo.shinyapps.io/Text-Prediction-Model"
  width="100%"
  height="800"
  frameborder="0"
  allowfullscreen>
</iframe>

</div>

<div class="project-buttons">


<a href="https://snndvl-martin-okwumuo.shinyapps.io/slide_deck"
   class="project-button">
    View Slide
</a>

<a href="projects/swiftkey-text-prediction-model/Text-Prediction-Model/Next_Word_Model_Case_Study.html"
   class="project-button">
    View Case Study
</a>

<a href="projects/swiftkey-text-prediction-model/Text-Prediction-Model/EDA_Report.html" class="project-button">
View EDA Report
</a>

<a href="https://github.com/okwumuo-martin/Text-Prediction-Model"
   target="_blank"
   class="project-button">
   View GitHub Repository
</a>


</div>

## German Credit Loan Eligibility Prediction App

 A machine-learning project using the German Credit dataset to analyze credit risk and develop an interactive loan eligibility prediction application using R and Shiny.

**Tools**

R | Shiny | Git | GitHub

**Skills Demonstrated**

- Exploratory Data Analysis
- Logistics Regression
- Product Thinking
- R Engineering
- Machine Learning

<div class="tableau-container">

<iframe
  src="https://snndvl-martin-okwumuo.shinyapps.io/Loan_eligibility_predictor"
  width="100%"
  height="800"
  frameborder="0"
  allowfullscreen>
</iframe>

</div>

<div class="project-buttons">


<a href="https://snndvl-martin-okwumuo.shinyapps.io/Loan_predictor_presentation"
   class="project-button">
    View Slide
</a>

<a href="projects/German-Credit-Predictor/German_Credit_Case_Study.html"
   class="project-button">
    View Case Study
</a>

<a href="projects/German-Credit-Predictor/EDA_Report_German_Credit.html" class="project-button">
View EDA Report
</a>

<a href="https://github.com/okwumuo-martin/German-Credit-Predictor"
   target="_blank"
   class="project-button">
   View GitHub Repository
</a>


</div>


```{=html}
<button onclick="topFunction()" id="topBtn">⬆</button>

<script>

window.onscroll=function(){

scrollFunction();

};

function scrollFunction(){

if(document.body.scrollTop>400||

document.documentElement.scrollTop>400){

document.getElementById("topBtn").style.display="block";

}else{

document.getElementById("topBtn").style.display="none";

}

}

function topFunction(){

window.scrollTo({

top:0,

behavior:'smooth'

});

}

</script>
```
